template = ""
rev_id = 5
template_sha = "b1bcc12f5675c5b86f53da0a290c53417f28d6e3"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "sjt"
__UND2C_TRG__ = "sjd"
__UNDEFINED_SOURCE__ = "Ter Saami"
__UNDEFINED_TARGET__ = "Kildin Saami"
__UND_SRC__ = "sjt"
__UND_TRG__ = "sjd"
